#!/usr/bin/perl -w

use strict;
use warnings;

use CGI;
use File::Temp qw/tempfile/;

my ($fh, $filename) = tempfile();

my $q = CGI->new();

my $data = $q->param('POSTDATA');

if(!defined($data)) {
	print $q->header("text/plain");
	print "E: Require an OCSP request\n";
	exit 0;
}

print $fh, $data;

print $q->header('application/ocsp-response');

open CONF, "/var/lib/eid/config";

my %conf;

while(<CONF>) {
	my @arr = split /=/;
	$arr[1] =~ s/"//g;
	$conf{$arr[0]} = $arr[1];
}

system("openssl ocsp -index /var/lib/eid/$conf{EID_TEST_CA_NAME}-index.txt -CA /var/lib/eid/$conf{EID_TEST_CA_NAME}.crt -resp_key_id -rkey /var/lib/eid/$conf{EID_TEST_CA_NAME}.key -nonce -respin $filename");
